name: Master App Auto Build
on:
  repository_dispatch:
    types: [trigger_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # અહીં v4 કર્યું ✅

      - name: Setup Java
        uses: actions/setup-java@v4 # અહીં v4 કર્યું ✅
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Download Merchant Logo
        run: |
          mkdir -p assets/images
          curl -L -o assets/images/merchant_logo.png "${{ github.event.client_payload.logo_url }}"

      - name: Change App Name
        run: |
          sed -i 's/android:label=".*"/android:label="${{ github.event.client_payload.app_name }}"/g' android/app/src/main/AndroidManifest.xml

      - name: Change Package ID
        run: |
          flutter pub get
          flutter pub run rename --bundleId ${{ github.event.client_payload.package_id }}

      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4 # અહીં મેઈન v4 કરવાનું છે ✅
        with:
          name: "${{ github.event.client_payload.app_name }}-APK"
          path: build/app/outputs/flutter-apk/app-release.apk
